//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 02/20/2022 21:42:17
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Unigram.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class Additional
    {
        
        private static ResourceLoader resourceLoader;
        
        /// <summary>
        /// Get or set ResourceLoader implementation
        /// </summary>
        public static ResourceLoader Resource
        {
            get
            {
                if ((resourceLoader == null))
                {
                    Additional.Initialize();
                }
                return resourceLoader;
            }
            set
            {
                resourceLoader = value;
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Play GIF previews on GIF selection"
        /// </summary>
        public static string PlayGifPreview
        {
            get
            {
                return Resource.GetString("PlayGifPreview");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Input device"
        /// </summary>
        public static string CallSettingInput
        {
            get
            {
                return Resource.GetString("CallSettingInput");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Microphone"
        /// </summary>
        public static string CallSettingInputTitle
        {
            get
            {
                return Resource.GetString("CallSettingInputTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Output device"
        /// </summary>
        public static string CallSettingOutput
        {
            get
            {
                return Resource.GetString("CallSettingOutput");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Speakers and headphones"
        /// </summary>
        public static string CallSettingOutputTitle
        {
            get
            {
                return Resource.GetString("CallSettingOutputTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Call Settings"
        /// </summary>
        public static string CallSettingsTitle
        {
            get
            {
                return Resource.GetString("CallSettingsTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Chats"
        /// </summary>
        public static string Chats
        {
            get
            {
                return Resource.GetString("Chats");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cut"
        /// </summary>
        public static string Cut
        {
            get
            {
                return Resource.GetString("Cut");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit Link"
        /// </summary>
        public static string EditLink
        {
            get
            {
                return Resource.GetString("EditLink");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "?"
        /// </summary>
        public static string FormatBoldGlyph
        {
            get
            {
                return Resource.GetString("FormatBoldGlyph");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "16"
        /// </summary>
        public static string FormatGlyphFontSize
        {
            get
            {
                return Resource.GetString("FormatGlyphFontSize");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "?"
        /// </summary>
        public static string FormatItalicGlyph
        {
            get
            {
                return Resource.GetString("FormatItalicGlyph");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Formatting"
        /// </summary>
        public static string Formatting
        {
            get
            {
                return Resource.GetString("Formatting");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Hide Formatting"
        /// </summary>
        public static string FormattingHide
        {
            get
            {
                return Resource.GetString("FormattingHide");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Show Formatting"
        /// </summary>
        public static string FormattingShow
        {
            get
            {
                return Resource.GetString("FormattingShow");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "?"
        /// </summary>
        public static string FormatUnderlineGlyph
        {
            get
            {
                return Resource.GetString("FormatUnderlineGlyph");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Input volume"
        /// </summary>
        public static string InputVolume
        {
            get
            {
                return Resource.GetString("InputVolume");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "News"
        /// </summary>
        public static string News
        {
            get
            {
                return Resource.GetString("News");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "original"
        /// </summary>
        public static string OriginalMessage
        {
            get
            {
                return Resource.GetString("OriginalMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Output volume"
        /// </summary>
        public static string OutputVolume
        {
            get
            {
                return Resource.GetString("OutputVolume");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Paste"
        /// </summary>
        public static string Paste
        {
            get
            {
                return Resource.GetString("Paste");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Redo"
        /// </summary>
        public static string Redo
        {
            get
            {
                return Resource.GetString("Redo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Replace Emoji"
        /// </summary>
        public static string ReplaceEmoji
        {
            get
            {
                return Resource.GetString("ReplaceEmoji");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select All"
        /// </summary>
        public static string SelectAll
        {
            get
            {
                return Resource.GetString("SelectAll");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Emoji Set"
        /// </summary>
        public static string SettingsEmojiSet
        {
            get
            {
                return Resource.GetString("SettingsEmojiSet");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Choose Emoji Set"
        /// </summary>
        public static string SettingsEmojiSetPopup
        {
            get
            {
                return Resource.GetString("SettingsEmojiSetPopup");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Thumbnails"
        /// </summary>
        public static string Thumbnails
        {
            get
            {
                return Resource.GetString("Thumbnails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Preview GIF animations"
        /// </summary>
        public static string SettingsThumbnailsGif
        {
            get
            {
                return Resource.GetString("SettingsThumbnailsGif");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Show Formatting Buttons"
        /// </summary>
        public static string SettingIsTextFormattingVisible
        {
            get
            {
                return Resource.GetString("SettingIsTextFormattingVisible");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "System Theme"
        /// </summary>
        public static string ThemeSystemTheme
        {
            get
            {
                return Resource.GetString("ThemeSystemTheme");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Undo"
        /// </summary>
        public static string Undo
        {
            get
            {
                return Resource.GetString("Undo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Play animated stickers"
        /// </summary>
        public static string SettingPlayStickers
        {
            get
            {
                return Resource.GetString("SettingPlayStickers");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Typing"
        /// </summary>
        public static string SettingsKeyboard
        {
            get
            {
                return Resource.GetString("SettingsKeyboard");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Highlight misspelled words"
        /// </summary>
        public static string SettingsHighlightWords
        {
            get
            {
                return Resource.GetString("SettingsHighlightWords");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Autocorrect misspelled words"
        /// </summary>
        public static string SettingsAutocorrectWords
        {
            get
            {
                return Resource.GetString("SettingsAutocorrectWords");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Folders at the top"
        /// </summary>
        public static string SettingsFoldersTabsAtTheTop
        {
            get
            {
                return Resource.GetString("SettingsFoldersTabsAtTheTop");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Folders on the left"
        /// </summary>
        public static string SettingsFoldersTabsOnTheLeft
        {
            get
            {
                return Resource.GetString("SettingsFoldersTabsOnTheLeft");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Folders view"
        /// </summary>
        public static string SettingsFoldersTabView
        {
            get
            {
                return Resource.GetString("SettingsFoldersTabView");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If you have many folders, try moving them to the left."
        /// </summary>
        public static string SettingsFoldersTabViewHint
        {
            get
            {
                return Resource.GetString("SettingsFoldersTabViewHint");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Other Chats"
        /// </summary>
        public static string SettingsStorageOtherChats
        {
            get
            {
                return Resource.GetString("SettingsStorageOtherChats");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Remove media captions in copies"
        /// </summary>
        public static string ShareRemoveCaptions
        {
            get
            {
                return Resource.GetString("ShareRemoveCaptions");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Send as copy"
        /// </summary>
        public static string ShareSendAsCopy
        {
            get
            {
                return Resource.GetString("ShareSendAsCopy");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Size of the folders menu"
        /// </summary>
        public static string SettingsFoldersLeftLayoutScale
        {
            get
            {
                return Resource.GetString("SettingsFoldersLeftLayoutScale");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Use system accent color"
        /// </summary>
        public static string SelectColorSystemAccent
        {
            get
            {
                return Resource.GetString("SelectColorSystemAccent");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Without Proxy"
        /// </summary>
        public static string ConnectWithoutProxy
        {
            get
            {
                return Resource.GetString("ConnectWithoutProxy");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Load all media"
        /// </summary>
        public static string LoadAllMedia
        {
            get
            {
                return Resource.GetString("LoadAllMedia");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Auto-download voice messages"
        /// </summary>
        public static string AutoDownloadAudioTitle
        {
            get
            {
                return Resource.GetString("AutoDownloadAudioTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Forward Selected"
        /// </summary>
        public static string SelectionForward
        {
            get
            {
                return Resource.GetString("SelectionForward");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Clear Selection"
        /// </summary>
        public static string SelectionClear
        {
            get
            {
                return Resource.GetString("SelectionClear");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Delete Selected"
        /// </summary>
        public static string SelectionDelete
        {
            get
            {
                return Resource.GetString("SelectionDelete");
            }
        }
        
        public static void Initialize()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Additional).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Additional");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Additional");
            }
        }
    }
}
